INSERT INTO `titre` (`libelleTitre`, `niveauRequis`, `idTheme`) VALUES
('The Last Crusader', '5', '3'),
('Raider of the Lost Ark', '10', '3'),
('Monkey Man', '15', '3'),
('For Fortune and Glory', '20', '3'),
('Archaeologist - Spy', '25', '3'),
('Captain Dynamite', '30', '3'),
('Pied velu', '5', '1'),
('Longues-barbes', '10', '1'),
('Haradrim', '15', '1'),
('Dunedain', '20', '1'),
('Cavalier de Nivacrin', '25', '1'),
('Nazgul', '30', '1'),
('Nécromancien', '35', '1'),
('Pèlerin gris', '40', '1'),
('Capitaine de la Tour Blanche', '45', '1'),
('Flamme de l\'Ouest', '50', '1'),
('Dame de Lorién', '55', '1'),
('Porteur d\'anneau', '60', '1'),
('Uruk-hai', '65', '1');