INSERT INTO `question` (`Illustration`, `libelleQuestion`, `answer`, `distracteur01`, `distracteur02`, `distracteur03`, `idTheme`) VALUES
(NULL, 'Radagast est l\'un des Istari, plus communément connus sous quelle appellation ?', 'Sorciers', 'Loup-garous', 'Guimpes', 'Rois sorciers', '1'),
(NULL, 'Qui étaient les Mírdains, qui avaient étudié avec Annatar durant trois cents ans ?', 'Des orfèvres', 'Des artificiers', 'Des magiciens', 'Des forgerons', '1'),
(NULL, 'Où Elrond est-il né ?', 'Aux Havres du Sirion', 'Sur les Hauteurs d\'Abraham', 'Dans les plaines de Dagorlad', 'En Ouistrenesse', '1'),
(NULL, 'Qui a donné à Sam une boîte contenant de la terre et une graine ?', 'Galadriel', 'Elrond', 'Faramir', 'Bilbon', '1'),
(NULL, 'Où J.R.R. Tolkien est-il né ?', 'En Afrique du Sud', 'En Angleterre', 'En Chine', 'En Terre du milieu', '1'),
(NULL, 'Quelle est la source de la lumière de la fiole de Galadriel ?', 'Lumière de l\'étoile d\Eärendil', 'Bougie', 'Puissantes batteries', 'Coeur de Tardis', '1'),
(NULL, 'Laquelle de ces propositions n\est pas une variété d\'herbe à pipe hobbite ?', 'Le cactus vrillé', 'L\'Étoile du Sud', 'le Vieux Tobie', 'La feuille de Langoulet', '1'),
(NULL, 'Qui est le roi de Dale à l\'époque des évènements du Seigneur des Anneaux ?', 'Brand', 'Gilion', 'Bard', 'Bain', '1'),
(NULL, 'Quelle était l\'ancienne capitale du Gondor ?', 'Osgiliath', 'Minas Morgul', 'Le Gourffre de Helm', 'Amon Dîn', '1'),
(NULL, 'Lequel n\'est PAS un titre de Gandalf ?', 'Loup Gris', 'Messager Gris', 'Vagabond Gris', 'Pélerin Gris', '1'),
(NULL, 'Sous quel nom signifiant « mauvaises nouvelles » Gandalf est-il introduit à la cour de Théoden ?', 'Lathspell', 'Maardahl', 'Portent', 'Briechraik', '1'),
(NULL, 'Selon le Prologue du Seigneur des Anneaux, la taille des Hobbits « est variable et va de ____ selon notre mesure ».', '60 cm à 1,20 m', '1,20 à 1,80 m', '30 à 90 cm', '90 cm à 1,50 m', '1'),
(NULL, 'Qui est « le Charpentier de navires » ?', 'Círdan', 'Celeborn', 'Glorfindel', 'Fingolfin', '1'),
(NULL, 'Laquelle de ces propositions n\'est PAS l\'un des noms de Tom Bombadil ?', 'Dervorin', 'Forn', 'Iarwain Ben-adar', 'Orald', '1'),
(NULL, 'In what Asian city and what year does "Indiana Jones and the Temple of Doom" open?', 'Shanghai 1935', 'Macao 1934', 'Chungking 1936', 'Hong Kong 1937', '3'),
(NULL, 'Sallah, in "Riaders of the Lost Ark", was married to whom?', 'Fayah', 'Kalila', 'Maryam', 'Basmah', '3'),
(NULL, 'Dr. Jones writes a word on the blackboard in "Raiders of the Lost Ark" explaining it from Greek for new and stone. What word?', 'Neolithic', 'Neoclassical', 'Neophilia', 'Neozoic', '3'),
(NULL, 'The Sankara Stones were used as a symbol of what aspect of Shiva?', 'Fertility', 'Fierceness', 'Fairness', 'Freedom', '3'),
(NULL, 'In "Raiders of the Lost Ark" where did Marion hid to escape the Cairo henchmen?', 'In a wicker basket', 'In a doorway', 'Under straw in a cart', 'In a ceramic pot', '3'),
(NULL, 'What is Indiana Jones\' father\'s name?', 'Henry', 'Frederick', 'Alfred', 'Bertram', '3'),
(NULL, 'What did Henry Jones, Sr. use to disable the Nazi soldier in the tank?', 'Pen', 'Sword', 'Grail diary', 'Luger', '3'),
(NULL, 'Complete this quote: "Across the desert and through the mountain to the ____"', 'Canyon of the Crescent Moon', 'Cave of the Rising Sun', 'Outpost of Hittite', 'Oasis of Suud', '3');